
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AudioProvider } from '../context/AudioContext'; // Asegúrate de importar el AudioProvider
import { SidebarProvider } from "@/context/SidebarContext";
import { SessionProvider } from "@/context/SessionContext";
import { ModalProvider } from "@/context/ModalContext";
import { ComentProvider } from "@/context/ComentContext";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Luz en el camino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ComentProvider>
          <ModalProvider>
            <SessionProvider>
              <SidebarProvider>
                <AudioProvider>
                  <ToastContainer/>
                  {children}
                </AudioProvider>
              </SidebarProvider>
            </SessionProvider>
          </ModalProvider>
        </ComentProvider>
      </body>
    </html>
  );
}
